# Permalinks
permalink:           pretty

# Setup
title:               Hồng Xuân Viên (Vien Hong)
tagline:             Back-End Engineering from Ho Chi Minh City.
url:                 http://vienhx.me
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jami Gibbs
  url:               https://twitter.com/jamigibbs
  email:             vien.hongxuan@gmail.com

# Custom vars
version:             2.0.1
github:
  repo:              https://github.com/vienhx/vienhx.github.io
google_analytics:    UA-174933187-1
twitter:             vienhx
github:              vienhx
linkedin:            vienhx
email:               vien.hongxuan@gmail.com

profile_url:
  linkedin:          https://www.linkedin.com/in/vienhx/
  github:            https://github.com/vienhx
  facebook:          https://www.facebook.com/vienhx/
  twitter:           https://twitter.com/vienhx
  resume:            https://vienhx.me/resume

# Gems
plugins:
  # - jekyll-paginate
  # - jekyll-gist
